dist: bionic

language: python
python:
  - "3.7"

env:
  global:
  - CODECOV_TOKEN="0fd7bec8-ba67-424a-a68c-aa8904ba1e80"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov requests
# command to run tests
script:
  - coverage run -m unittest discover
  - coverage xml
  - codecov